### ISSUE TITLE
Должен ли метод SumProfit быть публичным?

### ISSUE THREAD

**Issue by grinrill** [spacetab-io/my-bank-service#2]
Метод SumProfit может и должен использоваться только из метода AddFunds, он так же не должен вызываться извне, например по http api.

Поэтому мне показалось, что этот метод не должен быть публичным: можно сделать его приватным или даже убрать из AccountInterface.

**Comment by smgladkovskiy** [comment]
Да, Вы правы. Метод можно сделать приватным.
